import React from "react";
import { GeneratedReport } from "@/lib/api/reports";
import { FileText, ShieldAlert, Database, CheckCircle2, Sparkles, Layers, Clock, ExternalLink, Printer, Download, MapPin } from "lucide-react";
import { Link } from "@tanstack/react-router";

interface ReportPreviewProps {
  report: GeneratedReport | null;
  onPrint?: () => void;
  onExportJSON?: () => void;
  onExportCSV?: () => void;
}

export function ReportPreview({ report, onPrint, onExportJSON, onExportCSV }: ReportPreviewProps) {
  if (!report) {
    return (
      <div className="h-full w-full rounded-2xl border border-slate-800 bg-slate-950 p-8 flex flex-col items-center justify-center text-center font-mono text-slate-400">
        <FileText className="h-10 w-10 text-slate-600 mb-2 animate-bounce" />
        <p className="text-xs font-bold">Select a report template and target entity to generate a live report preview.</p>
      </div>
    );
  }

  const d = report.data;

  return (
    <div className="w-full bg-slate-900/90 border border-slate-800 rounded-2xl p-6 shadow-2xl space-y-6 text-slate-100 font-sans backdrop-blur-xl">
      
      {/* 1. Header Toolbar */}
      <div className="flex items-center justify-between border-b border-slate-800 pb-4">
        <div className="flex items-center gap-2">
          <span className="px-2.5 py-1 rounded-lg bg-teal-500/10 border border-teal-500/30 text-teal-300 font-mono text-[11px] font-bold">
            {report.reportType.replace(/_/g, " ")}
          </span>
          <span className="px-2.5 py-1 rounded-lg bg-purple-500/10 border border-purple-500/30 text-purple-300 font-mono text-[11px] font-bold">
            SYNTHETIC DEMO DATA
          </span>
        </div>

        <div className="flex items-center gap-2 font-mono text-xs">
          {onPrint && (
            <button
              onClick={onPrint}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-gradient-to-r from-teal-600 to-cyan-600 hover:from-teal-500 hover:to-cyan-500 text-white font-bold transition shadow-lg"
            >
              <Printer className="h-3.5 w-3.5" />
              DOWNLOAD PDF
            </button>
          )}
          {onExportJSON && (
            <button
              onClick={onExportJSON}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-teal-300 font-bold transition"
            >
              <Download className="h-3.5 w-3.5" />
              JSON
            </button>
          )}
          {onExportCSV && (
            <button
              onClick={onExportCSV}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-cyan-300 font-bold transition"
            >
              <Download className="h-3.5 w-3.5" />
              CSV
            </button>
          )}
        </div>
      </div>

      {/* 2. Official BHOO-MITRA AI Report Document Frame */}
      <div className="p-8 rounded-2xl bg-slate-950 border border-slate-800/80 space-y-6 shadow-2xl">
        
        {/* Document Title Header */}
        <div className="border-b border-slate-800 pb-4 flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2 text-xs font-mono font-bold text-teal-400">
              <span className="h-2 w-2 rounded-full bg-teal-400" />
              BHOO-MITRA AI — LAND INTELLIGENCE PLATFORM
            </div>
            <h1 className="text-2xl font-black font-display text-white mt-1">{report.title}</h1>
            <div className="text-xs font-mono text-slate-400 mt-1">
              Report ID: {report.reportId} • Target Entity: {report.targetId}
            </div>
          </div>

          <div className="font-mono text-right text-xs text-slate-400 space-y-0.5">
            <div>Generated: <span className="text-slate-200">{new Date(report.createdAt).toLocaleString()}</span></div>
            <div>Generated By: <span className="text-teal-300">{report.createdBy}</span></div>
            <div>Status: <span className="text-emerald-400 font-bold">{report.status}</span></div>
          </div>
        </div>

        {/* Executive Summary */}
        <div className="p-4 rounded-xl bg-slate-900/80 border border-slate-800 space-y-2">
          <div className="font-mono text-xs font-bold text-teal-400 uppercase tracking-wider flex items-center gap-1.5">
            <FileText className="h-4 w-4" />
            1. EXECUTIVE SUMMARY
          </div>
          <p className="text-xs text-slate-300 leading-relaxed font-sans">{report.summaryText}</p>
        </div>

        {/* Spatial & Parcel Information */}
        {d.parcelId && (
          <div className="space-y-3">
            <div className="font-mono text-xs font-bold text-teal-400 uppercase tracking-wider flex items-center gap-1.5">
              <MapPin className="h-4 w-4" />
              2. PARCEL & SPATIAL IDENTITY
            </div>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 font-mono text-xs p-4 rounded-xl bg-slate-900/60 border border-slate-800">
              <div>
                <div className="text-[10px] text-slate-500">Parcel ID</div>
                <div className="font-bold text-slate-100">{d.parcelId}</div>
              </div>
              <div>
                <div className="text-[10px] text-slate-500">Parcel Area</div>
                <div className="font-bold text-slate-100">{d.areaSqM} m²</div>
              </div>
              <div>
                <div className="text-[10px] text-slate-500">Perimeter</div>
                <div className="font-bold text-slate-100">{d.perimeterM} m</div>
              </div>
              <div>
                <div className="text-[10px] text-slate-500">Buildings Count</div>
                <div className="font-bold text-teal-300">{d.buildingsCount}</div>
              </div>
            </div>
          </div>
        )}

        {/* Source Comparison */}
        {d.sources && (
          <div className="space-y-3">
            <div className="font-mono text-xs font-bold text-teal-400 uppercase tracking-wider flex items-center gap-1.5">
              <Database className="h-4 w-4" />
              3. SOURCE OBSERVATION COMPARISON
            </div>
            <div className="divide-y divide-slate-800 border border-slate-800 rounded-xl overflow-hidden font-mono text-xs">
              <div className="bg-slate-900 p-2.5 grid grid-cols-3 font-bold text-slate-400 text-[10px] uppercase">
                <span>Source Name</span>
                <span>Confidence Rating</span>
                <span>Represented Area</span>
              </div>
              {d.sources.map((src, i) => (
                <div key={i} className="p-2.5 grid grid-cols-3 bg-slate-950/60 text-slate-200">
                  <span className="font-bold text-teal-300">{src.name}</span>
                  <span>{Math.round(src.confidence * 100)}%</span>
                  <span>{src.area} m²</span>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Geometry Difference Metrics */}
        {d.geometryDifference && (
          <div className="space-y-3">
            <div className="font-mono text-xs font-bold text-purple-400 uppercase tracking-wider flex items-center gap-1.5">
              <Layers className="h-4 w-4" />
              4. DETERMINISTIC GEOMETRY DIFFERENCE
            </div>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 font-mono text-xs p-4 rounded-xl bg-slate-900/60 border border-slate-800">
              <div>
                <div className="text-[10px] text-slate-500">Area Difference</div>
                <div className="font-bold text-amber-400">{d.geometryDifference.areaDiff} m²</div>
              </div>
              <div>
                <div className="text-[10px] text-slate-500">Centroid Shift</div>
                <div className="font-bold text-amber-400">{d.geometryDifference.centroidShiftM} m</div>
              </div>
              <div>
                <div className="text-[10px] text-slate-500">Overlap Ratio</div>
                <div className="font-bold text-teal-300">{Math.round(d.geometryDifference.overlapRatio * 100)}%</div>
              </div>
              <div>
                <div className="text-[10px] text-slate-500">IoU Score</div>
                <div className="font-bold text-teal-300">{d.geometryDifference.iou}</div>
              </div>
            </div>
          </div>
        )}

        {/* AI Recommendation & Human Verification Side-by-Side */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          
          {/* AI Recommendation */}
          {d.recommendation && (
            <div className="p-4 rounded-xl bg-indigo-950/40 border border-indigo-500/30 font-mono text-xs space-y-2">
              <div className="font-bold text-indigo-300 flex items-center gap-1.5">
                <Sparkles className="h-4 w-4" />
                AI-ASSISTED HARMONIZATION RECOMMENDATION
              </div>
              <div className="text-slate-300 text-[11px] font-sans">{d.recommendation.action}</div>
              <div className="text-[10px] text-indigo-400 font-bold">Confidence: {Math.round(d.recommendation.confidence * 100)}%</div>
            </div>
          )}

          {/* Human Verification */}
          {d.verification && (
            <div className="p-4 rounded-xl bg-teal-950/40 border border-teal-500/30 font-mono text-xs space-y-2">
              <div className="font-bold text-teal-300 flex items-center gap-1.5">
                <CheckCircle2 className="h-4 w-4" />
                HUMAN VERIFICATION STATE
              </div>
              <div className="text-slate-300 text-[11px]">Status: <span className="font-bold text-emerald-400">{d.verification.status}</span></div>
              <div className="text-[10px] text-teal-400">Assigned Role: {d.verification.assignedRole}</div>
            </div>
          )}

        </div>

        {/* Provenance Audit Integrity Panel */}
        <div className="p-4 rounded-xl bg-slate-900/80 border border-slate-800 font-mono text-xs space-y-2">
          <div className="font-bold text-slate-400 flex items-center justify-between text-[11px]">
            <span>REPORT PROVENANCE & INTEGRITY CHECKLIST</span>
            <span className="text-teal-400 font-bold">PROVENANCE VERIFIED</span>
          </div>
          <div className="grid grid-cols-2 sm:grid-cols-5 gap-2 text-[10px] text-slate-300">
            <div>Source Feeds: <span className="text-teal-300 font-bold">✓ 3 Feeds</span></div>
            <div>Conflict Refs: <span className="text-teal-300 font-bold">✓ Matched</span></div>
            <div>Evidence Chain: <span className="text-teal-300 font-bold">✓ 5 Records</span></div>
            <div>Audit Events: <span className="text-teal-300 font-bold">✓ 14 Events</span></div>
            <div>Demo Label: <span className="text-purple-300 font-bold">✓ Included</span></div>
          </div>
        </div>

        {/* Governance Disclaimer */}
        <div className="pt-4 border-t border-slate-800 text-center font-mono text-[10px] text-slate-500 leading-relaxed">
          {d.governanceDisclaimer || "BHOO-MITRA AI provides analytical decision support. AI-generated recommendations do not replace authorized human review or official government land records."}
        </div>

      </div>

    </div>
  );
}
