SYNTHETIC_CONFLICTS_DATA = [
    {
        "id": "CF-1042",
        "entityId": "CANONICAL-014",
        "parcelId": "PARCEL-DEMO-014",
        "conflictType": "Boundary Discrepancy & Area Discrepancy",
        "severity": "HIGH",
        "status": "OPEN",
        "description": "Municipal GIS records area as 2,430 m² while Title Deed records 2,510 m² (80 m² boundary offset).",
        "sourcesInvolved": ["Municipal GIS", "Property Registry", "Survey Dataset"],
        "areaDiscrepancySqm": 80.0,
        "detectedAt": "2026-09-20T10:30:00Z",
        "evidenceIds": ["EVID-GEOM-014", "EVID-DEED-98102"],
        "suggestedResolution": "Adopt high-precision GNSS Field Survey SP-2291 boundary vector (2,465 m²).",
    },
    {
        "id": "CF-1043",
        "entityId": "CANONICAL-018",
        "parcelId": "PARCEL-DEMO-018",
        "conflictType": "Zoning & Land Use Conflict",
        "severity": "MEDIUM",
        "status": "REVIEW",
        "description": "Municipal zoning classified as Commercial C-2 while Revenue Record lists Residential R-1.",
        "sourcesInvolved": ["Municipal GIS", "Planning Dataset"],
        "areaDiscrepancySqm": 0.0,
        "detectedAt": "2026-09-18T14:15:00Z",
        "evidenceIds": ["EVID-PLAN-ZONE41"],
        "suggestedResolution": "Confirm Master Plan 2041 commercial gazette notification.",
    },
]
