SYNTHETIC_SOURCES_DATA = [
    {
        "id": "MUNI-GIS-WARD18",
        "name": "Municipal GIS Ward 18",
        "type": "Government GIS",
        "format": "GeoJSON",
        "status": "CONNECTED",
        "organization": "Delhi Municipal Corporation (DMC) GIS Cell",
        "contactEmail": "gis-cell@dmc.gov.in",
        "description": "Official municipal spatial parcel register digitized from Ward 18 cadastral map sheets.",
        "entityCount": 18240,
        "assetCount": 3,
        "lastUpdated": "2026-09-24T16:20:00Z",
        "spatial": {
            "crs": "EPSG:4326",
            "crsName": "WGS 84 / World Geodetic System 1984",
            "targetCrs": "EPSG:4326",
            "transformationName": "Identity / WGS84 Direct Mapping",
            "geometryType": "Polygon",
            "bbox": [77.201, 28.599, 77.205, 28.604],
            "coveragePercentage": 98.5,
            "spatialExtentDescription": "Delhi Ward 18 Commercial & Mixed Sector",
            "accuracyMeters": 0.25,
        },
        "temporal": {
            "observationDate": "2024-04-12",
            "lastUpdated": "2026-09-24T16:20:00Z",
            "dataVintage": "FY 2024-25 Revision",
            "updateFrequency": "Monthly",
        },
        "quality": {
            "completeness": 94,
            "geometryValidity": 97,
            "attributeCompleteness": 91,
            "crsValidity": 100,
            "duplicateRate": 2,
            "overallQualityScore": 94.2,
            "weights": {"geometry": 0.3, "attributes": 0.25, "completeness": 0.2, "crs": 0.15, "duplicates": 0.1},
        },
        "reliability": {
            "score": 92,
            "level": "High",
            "historicalConsistency": 95,
            "geometryQuality": 92,
            "attributeQuality": 89,
            "temporalFreshness": 90,
            "verificationHistoryCount": 420,
        },
        "schema": [
            {"name": "parcel_id", "type": "string", "nullable": False, "example": "P-10482", "description": "Municipal tax parcel ID"},
            {"name": "land_use", "type": "string", "nullable": True, "example": "Residential - Mixed", "description": "Zoning category"},
            {"name": "area_sqm", "type": "number", "nullable": False, "example": "2430.0", "description": "Digitized polygon area"},
            {"name": "ward_no", "type": "string", "nullable": False, "example": "Ward 18", "description": "Administrative ward"},
        ],
        "assets": [
            {"id": "AST-MUNI-01", "sourceId": "MUNI-GIS-WARD18", "name": "municipal_parcels.geojson", "assetType": "parcels", "format": "GeoJSON", "sizeMb": 14.8, "featureCount": 18240, "crs": "EPSG:4326", "lastUpdated": "2026-09-24", "status": "READY"},
            {"id": "AST-MUNI-02", "sourceId": "MUNI-GIS-WARD18", "name": "municipal_buildings.geojson", "assetType": "buildings", "format": "GeoJSON", "sizeMb": 32.4, "featureCount": 24100, "crs": "EPSG:4326", "lastUpdated": "2026-09-20", "status": "READY"},
        ],
        "validation": {
            "passed": True,
            "summary": {"geometry": "PASS", "crs": "PASS", "schema": "WARNING", "duplicates": "PASS", "requiredFields": "PASS", "missingAttributes": "WARNING"},
            "warnings": [{"code": "ATTR_NULL_TAX", "message": "Tax status field contains 6% null attributes.", "severity": "LOW"}],
            "errors": [],
        },
        "observedEntityIds": ["PARCEL-DEMO-014", "PARCEL-DEMO-015"],
    },
    {
        "id": "REGISTRY-PROP-014",
        "name": "Property Registry Register",
        "type": "Land Registry",
        "format": "GeoJSON / Tabular",
        "status": "READY",
        "organization": "Department of Revenue & Land Records (Sub-Registrar IX)",
        "contactEmail": "subregistrar-ix@delhi.gov.in",
        "description": "Legal title deeds, conveyance records, and boundary descriptions recorded during legal transactions.",
        "entityCount": 14500,
        "assetCount": 2,
        "lastUpdated": "2026-09-25T12:15:00Z",
        "spatial": {
            "crs": "EPSG:4326",
            "crsName": "WGS 84 / World Geodetic System 1984",
            "targetCrs": "EPSG:4326",
            "transformationName": "Identity Direct Mapping",
            "geometryType": "Polygon",
            "bbox": [77.201, 28.599, 77.205, 28.604],
            "coveragePercentage": 94.0,
            "spatialExtentDescription": "Sub-Registrar District IX Title Records",
            "accuracyMeters": 0.5,
        },
        "temporal": {
            "observationDate": "2025-11-04",
            "lastUpdated": "2026-09-25T12:15:00Z",
            "dataVintage": "Current Deed Records",
            "updateFrequency": "Real-time",
        },
        "quality": {
            "completeness": 91,
            "geometryValidity": 89,
            "attributeCompleteness": 98,
            "crsValidity": 100,
            "duplicateRate": 1,
            "overallQualityScore": 91.8,
            "weights": {"geometry": 0.3, "attributes": 0.25, "completeness": 0.2, "crs": 0.15, "duplicates": 0.1},
        },
        "reliability": {
            "score": 95,
            "level": "High",
            "historicalConsistency": 96,
            "geometryQuality": 88,
            "attributeQuality": 98,
            "temporalFreshness": 97,
            "verificationHistoryCount": 510,
        },
        "schema": [
            {"name": "deed_no", "type": "string", "nullable": False, "example": "REG-98102", "description": "Registered deed index"},
            {"name": "owner_name", "type": "string", "nullable": False, "example": "Devi Sharan & Sons", "description": "Owner name"},
        ],
        "assets": [
            {"id": "AST-REG-01", "sourceId": "REGISTRY-PROP-014", "name": "registry_parcels.geojson", "assetType": "parcels", "format": "GeoJSON", "sizeMb": 18.4, "featureCount": 14500, "crs": "EPSG:4326", "lastUpdated": "2026-09-25", "status": "READY"}
        ],
        "validation": {
            "passed": True,
            "summary": {"geometry": "WARNING", "crs": "PASS", "schema": "PASS", "duplicates": "PASS", "requiredFields": "PASS", "missingAttributes": "PASS"},
            "warnings": [],
            "errors": [],
        },
        "observedEntityIds": ["PARCEL-DEMO-014"],
    },
]
