/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppConflictsRouteImport } from './routes/_app/conflicts'
import { Route as AppDataSourcesRouteImport } from './routes/_app/data-sources'
import { Route as AppEntityMatchingRouteImport } from './routes/_app/entity-matching'
import { Route as AppEvidenceRouteImport } from './routes/_app/evidence'
import { Route as AppHarmonizationRouteImport } from './routes/_app/harmonization'
import { Route as AppIntelligence3dRouteImport } from './routes/_app/intelligence-3d'
import { Route as AppMapRouteImport } from './routes/_app/map'
import { Route as AppOverviewRouteImport } from './routes/_app/overview'
import { Route as AppRecordsRouteImport } from './routes/_app/records'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSourcesRouteImport } from './routes/_app/sources'
import { Route as AppSpatialQueryRouteImport } from './routes/_app/spatial-query'
import { Route as AppVerificationRouteImport } from './routes/_app/verification'
import { Route as AppSettingsUsersRouteImport } from './routes/_app/settings/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppConflictsRoute = AppConflictsRouteImport.update({
  id: '/conflicts',
  path: '/conflicts',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDataSourcesRoute = AppDataSourcesRouteImport.update({
  id: '/data-sources',
  path: '/data-sources',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEntityMatchingRoute = AppEntityMatchingRouteImport.update({
  id: '/entity-matching',
  path: '/entity-matching',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEvidenceRoute = AppEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHarmonizationRoute = AppHarmonizationRouteImport.update({
  id: '/harmonization',
  path: '/harmonization',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppIntelligence3dRoute = AppIntelligence3dRouteImport.update({
  id: '/intelligence-3d',
  path: '/intelligence-3d',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRecordsRoute = AppRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSourcesRoute = AppSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSpatialQueryRoute = AppSpatialQueryRouteImport.update({
  id: '/spatial-query',
  path: '/spatial-query',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVerificationRoute = AppVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsUsersRoute = AppSettingsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppSettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/audit': typeof AppAuditRoute
  '/conflicts': typeof AppConflictsRoute
  '/data-sources': typeof AppDataSourcesRoute
  '/entity-matching': typeof AppEntityMatchingRoute
  '/evidence': typeof AppEvidenceRoute
  '/harmonization': typeof AppHarmonizationRoute
  '/intelligence-3d': typeof AppIntelligence3dRoute
  '/map': typeof AppMapRoute
  '/overview': typeof AppOverviewRoute
  '/records': typeof AppRecordsRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/sources': typeof AppSourcesRoute
  '/spatial-query': typeof AppSpatialQueryRoute
  '/verification': typeof AppVerificationRoute
  '/settings/users': typeof AppSettingsUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AppAnalyticsRoute
  '/audit': typeof AppAuditRoute
  '/conflicts': typeof AppConflictsRoute
  '/data-sources': typeof AppDataSourcesRoute
  '/entity-matching': typeof AppEntityMatchingRoute
  '/evidence': typeof AppEvidenceRoute
  '/harmonization': typeof AppHarmonizationRoute
  '/intelligence-3d': typeof AppIntelligence3dRoute
  '/map': typeof AppMapRoute
  '/overview': typeof AppOverviewRoute
  '/records': typeof AppRecordsRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/sources': typeof AppSourcesRoute
  '/spatial-query': typeof AppSpatialQueryRoute
  '/verification': typeof AppVerificationRoute
  '/settings/users': typeof AppSettingsUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/conflicts': typeof AppConflictsRoute
  '/_app/data-sources': typeof AppDataSourcesRoute
  '/_app/entity-matching': typeof AppEntityMatchingRoute
  '/_app/evidence': typeof AppEvidenceRoute
  '/_app/harmonization': typeof AppHarmonizationRoute
  '/_app/intelligence-3d': typeof AppIntelligence3dRoute
  '/_app/map': typeof AppMapRoute
  '/_app/overview': typeof AppOverviewRoute
  '/_app/records': typeof AppRecordsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/sources': typeof AppSourcesRoute
  '/_app/spatial-query': typeof AppSpatialQueryRoute
  '/_app/verification': typeof AppVerificationRoute
  '/_app/settings/users': typeof AppSettingsUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analytics'
    | '/audit'
    | '/conflicts'
    | '/data-sources'
    | '/entity-matching'
    | '/evidence'
    | '/harmonization'
    | '/intelligence-3d'
    | '/map'
    | '/overview'
    | '/records'
    | '/reports'
    | '/settings'
    | '/sources'
    | '/spatial-query'
    | '/verification'
    | '/settings/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/analytics'
    | '/audit'
    | '/conflicts'
    | '/data-sources'
    | '/entity-matching'
    | '/evidence'
    | '/harmonization'
    | '/intelligence-3d'
    | '/map'
    | '/overview'
    | '/records'
    | '/reports'
    | '/settings'
    | '/sources'
    | '/spatial-query'
    | '/verification'
    | '/settings/users'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/analytics'
    | '/_app/audit'
    | '/_app/conflicts'
    | '/_app/data-sources'
    | '/_app/entity-matching'
    | '/_app/evidence'
    | '/_app/harmonization'
    | '/_app/intelligence-3d'
    | '/_app/map'
    | '/_app/overview'
    | '/_app/records'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/sources'
    | '/_app/spatial-query'
    | '/_app/verification'
    | '/_app/settings/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/conflicts': {
      id: '/_app/conflicts'
      path: '/conflicts'
      fullPath: '/conflicts'
      preLoaderRoute: typeof AppConflictsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/data-sources': {
      id: '/_app/data-sources'
      path: '/data-sources'
      fullPath: '/data-sources'
      preLoaderRoute: typeof AppDataSourcesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/entity-matching': {
      id: '/_app/entity-matching'
      path: '/entity-matching'
      fullPath: '/entity-matching'
      preLoaderRoute: typeof AppEntityMatchingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/evidence': {
      id: '/_app/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof AppEvidenceRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/harmonization': {
      id: '/_app/harmonization'
      path: '/harmonization'
      fullPath: '/harmonization'
      preLoaderRoute: typeof AppHarmonizationRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/intelligence-3d': {
      id: '/_app/intelligence-3d'
      path: '/intelligence-3d'
      fullPath: '/intelligence-3d'
      preLoaderRoute: typeof AppIntelligence3dRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/map': {
      id: '/_app/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/overview': {
      id: '/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/records': {
      id: '/_app/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof AppRecordsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/sources': {
      id: '/_app/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof AppSourcesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/spatial-query': {
      id: '/_app/spatial-query'
      path: '/spatial-query'
      fullPath: '/spatial-query'
      preLoaderRoute: typeof AppSpatialQueryRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/verification': {
      id: '/_app/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof AppVerificationRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/users': {
      id: '/_app/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AppSettingsUsersRouteImport
      parentRoute: typeof AppSettingsRoute
    }
  }
}

interface AppSettingsRouteChildren {
  AppSettingsUsersRoute: typeof AppSettingsUsersRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsUsersRoute: AppSettingsUsersRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppConflictsRoute: typeof AppConflictsRoute
  AppDataSourcesRoute: typeof AppDataSourcesRoute
  AppEntityMatchingRoute: typeof AppEntityMatchingRoute
  AppEvidenceRoute: typeof AppEvidenceRoute
  AppHarmonizationRoute: typeof AppHarmonizationRoute
  AppIntelligence3dRoute: typeof AppIntelligence3dRoute
  AppMapRoute: typeof AppMapRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppRecordsRoute: typeof AppRecordsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppSourcesRoute: typeof AppSourcesRoute
  AppSpatialQueryRoute: typeof AppSpatialQueryRoute
  AppVerificationRoute: typeof AppVerificationRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAuditRoute: AppAuditRoute,
  AppConflictsRoute: AppConflictsRoute,
  AppDataSourcesRoute: AppDataSourcesRoute,
  AppEntityMatchingRoute: AppEntityMatchingRoute,
  AppEvidenceRoute: AppEvidenceRoute,
  AppHarmonizationRoute: AppHarmonizationRoute,
  AppIntelligence3dRoute: AppIntelligence3dRoute,
  AppMapRoute: AppMapRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppRecordsRoute: AppRecordsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppSourcesRoute: AppSourcesRoute,
  AppSpatialQueryRoute: AppSpatialQueryRoute,
  AppVerificationRoute: AppVerificationRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
